-- VIEWS
-- CREATE VIEW VIEW_NAME AS
--  1) SELECT column1, column2, ...  OR
--  2) FROM SELECT FROM * TABLE_NAME  OR
--  3) SWHERE condition; 


USE HR;

CREATE TABLE V AS SELECT * FROM EMPLOYEES;
SELECT * FROM V;


create view v_v as select emp_id, first_name, last_name, job_id,manager_id, DEPARTMENT_ID
from employees;

CREATE VIEW V_V AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY, DEPARTMENT_ID
FROM EMPLOYEES;
SELECT * FROM V_V;

ALTER VIEW V_V AS SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, JOB_ID, MANAGER_ID, DEPARTMENT_ID,
COMMISSION_PCT FROM EMPLOYEES;
SELECT * FROM V_V;

SELECT EMPLOYEE_ID, FIRST_NAME, MANAGER_ID FROM V_V
WHERE MANAGER_ID = 100;


DROP VIEW V_V; 
