-- DATA MANIPULATION LANGUAGE
-- NOT ON AUTOSAVE MODE
-- UPDATE, INSERT, DELETE


-- INSERT

USE HR;

SELECT * FROM CAREER1;

INSERT INTO CAREER1 VALUES (1, 'SURAJ', 'HK', 9000);
SELECT * FROM CAREER1;

INSERT INTO CAREER1 VALUES (2, 'SUSH', 'NK', 8000),
						   (3, 'AKRAM', 'NANDGAVE', 9800),
                           (4, 'NAZMIN', 'DHIRU', 9000);
SELECT * FROM CAREER1;

INSERT INTO CAREER1 (FIRST_NAME, SURENAME) VALUES ('SHIVU','MT');
SELECT * FROM CAREER1;

INSERT INTO CAREER1 (EMPLOYEE_ID, SALARY) VALUES (5, 5000);
SELECT * FROM CAREER1;

INSERT INTO CAREER1 (EMPLOYEE_ID, SALARY) VALUES (6, 5000);
SELECT * FROM CAREER1;

INSERT INTO CAREER1 VALUES (7, 'ANIKET', 'JADHAV', NULL);
SELECT * FROM CAREER1;



-- UPDATE

SELECT * FROM CAREER1;

UPDATE CAREER1
SET EMPLOYEE_ID = 9 
WHERE FIRST_NAME = 'SHIVU';
SELECT * FROM CAREER1;

UPDATE CAREER1
SET SALARY = 9900
WHERE EMPLOYEE_ID = 9;
SELECT * FROM CAREER1;

UPDATE CAREER1
SET FIRST_NAME = 'RAHUL', SURENAME = 'DQ'
WHERE EMPLOYEE_ID = 5;
SELECT * FROM CAREER1;

UPDATE CAREER1
SET FIRST_NAME = 'ARIF', SURENAME = 'MD'
WHERE EMPLOYEE_ID = 6;
SELECT * FROM CAREER1;

UPDATE CAREER1
SET SALARY = 7000
WHERE EMPLOYEE_ID=7;
SELECT * FROM CAREER1;



-- DELETE

DELETE  FROM CAREER1
WHERE EMPLOYEE_ID=9;
SELECT * FROM CAREER1;


UPDATE EMP_PRACTICE1 
SET JOB_ID = 'DIRECTOR'
WHERE EMPLOYEE_ID= 100;
SELECT * FROM EMP_PRACTICE1;

UPDATE EMP_PRACTICE1
SET JOB_ID = 'CEO', 
SALARY= 10000,
PHONE_NUMBER= '123,456,789'
WHERE EMPLOYEE_ID = 100;
SELECT * FROM EMP_PRACTICE1;
