-- INDEX
-- SYNTAX

USE HR;

SELECT * FROM EMPLOYEES
WHERE SALARY > 9000;


-- CREATING INDEX
-- CREATE INDEX INDEX_NAME ON TABLE_NAME (COL1,COL2, ....);

CREATE TABLE ABC(
EMP_ID INT UNSIGNED PRIMARY KEY,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
SALARY DECIMAL(7,3));

SELECT *FROM ABC;

SHOW INDEX FROM ABC;

CREATE INDEX ABC_IDX ON ABC (LAST_NAME, SALARY);
SHOW INDEX FROM ABC;


-- CREATING AN UNIQUE INDEX
-- CREATE UNIQUE INDEX INDEX_NAME ON TABLE_NAME (COL1, COL2, ....);

CREATE UNIQUE INDEX ABC_IDX1 ON ABC (EMP_ID, SALARY);
SHOW INDEX FROM ABC;


-- DROPING AN INDEX
-- ALTER TABLE TABLE_NAME DROP INDEX INDEX_NAME;

ALTER TABLE ABC DROP INDEX ABC_IDX1;
SHOW INDEX FROM ABC;

