-- PARAMETERS IN MYSQL

-- 1. * -- FETCH COLUMN NAMES
-- 2. WHERE -- CONDITION
-- 3. GROUP BY -- GROUP DATA BY ONE OR MORE COLUMNS
-- 4. HAVING  -- WORK WITH GROUP BY CALUSE RETURN IF CONDITION IS SATIFY
-- 5. ORDER BY -- SORT THE DATA
-- 6. OFFSET  -- SPECIFYY WHICH ROW RETURNS FIRST, DEFAULT START WITH 0
-- 7. LIMIT  -- LIMIT THE NUMBER OF RECORDS RETURNED

-- 1. * 

USE HR;

SELECT * FROM EMPLOYEES;



-- 2. WHERE 

-- SINGLE CONDITION

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID >180;

-- MULTIPLE CONDITIONS
-- USING 'AND' LOGICAL OPERATOR
SELECT * FROM EMPLOYEES
WHERE SALARY>10000 AND SALARY <20000;

-- USING 'OR' LOGICAL OPERATOR
SELECT * FROM EMPLOYEES
WHERE SALARY > 10000 OR JOB_ID='AD_VP';

-- USING 'NOT' LOGICAL OPERATOR
SELECT * FROM EMPLOYEES
WHERE NOT SALARY>10000;

-- USING MULTIPLE LOGICAL OPERATOR
SELECT * FROM EMPLOYEES
WHERE (SALARY >20000 AND SALARY<30000) OR HIRE_DATE > '2000-01-01';


-- 3. ORDER BY
-- ASCENDING
SELECT SALARY FROM EMPLOYEES
ORDER BY SALARY ASC;

-- DESCENDING
SELECT SALARY FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT * FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

SELECT * FROM EMPLOYEES
ORDER BY FIRST_NAME DESC;

-- ORDER BY WITH WHERE CONDITION
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE > '1998-01-01'
ORDER BY SALARY DESC;

-- ORDER BY WITH BOTH ASC & DESC
SELECT * FROM EMPLOYEES
ORDER BY JOB_ID ASC, SALARY DESC;

-- SORTING BY POSITION

SELECT * FROM EMPLOYEES
ORDER BY 6 ASC;

SELECT EMPLOYEE_ID EMP_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT FROM EMPLOYEES
ORDER BY 5;

SELECT EMPLOYEE_ID EMP_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT FROM EMPLOYEES
ORDER BY 5 DESC;


-- 4. GROUP BY WITH SUM, COUNT, MIN, MAX
SELECT  SALARY, JOB_ID, COUNT(*) FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT  MAX(SALARY), JOB_ID FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT  MIN(SALARY), JOB_ID FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT 
    AVG(SALARY), JOB_ID
FROM
    EMPLOYEES
GROUP BY JOB_ID;



-- 5. LIMIT

SELECT SALARY FROM EMPLOYEES
LIMIT 5;

SELECT EMPLOYEE_ID EMP_ID, FIRST_NAME, LAST_NAME, JOB_ID, SALARY, COMMISSION_PCT FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 5;

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
ORDER BY FIRST_NAME
LIMIT 5; 
   


-- 5. OFFSET 
-- OFFSET can only be used with ORDER BY clause. It cannot be used on its own.

SELECT FIRST_NAME, LAST_NAME FROM EMPLOYEES
ORDER BY FIRST_NAME
LIMIT 5 OFFSET 3;


SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 1 OFFSET 1;



-- 7. HAVING

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID >150
HAVING SALARY=10000;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID >150
GROUP BY FIRST_NAME
HAVING SALARY=10000;