-- TCL(TRANSACTION CONTROL LANGUAGE)
-- COMMITE (LIKE CTR+S IN EXCEL)
-- ROLLBACK (LIKE CTR+Z IN EXCEL)



USE HR;

SELECT * FROM CAREERERA1;
DESC CAREERERA1;

ALTER TABLE CAREERERA1 MODIFY DEPARTMENT_ID VARCHAR(2);
DESC CAREERERA1;

INSERT INTO CAREERERA1 VALUES (1, 101, 'SURAJ', 'HONKAMBLE', 25000, 'DS');
SELECT * FROM CAREERERA1;

INSERT INTO CAREERERA1 VALUES (2, 102, 'SUSHMITA', 'NAIK', 30000, 'DA');
SELECT * FROM CAREERERA1;

ROLLBACK;
SELECT * FROM CAREERERA1;

INSERT INTO CAREERERA1 VALUES (1, 101, 'SURAJ', 'HONKAMBLE', 25000, 'DS'),
							  (2, 102, 'SUSHMITA', 'NAIK', 30000, 'DA'),
                              (3, 103, 'SWAPNIL', 'KAMBLE', 25000, 'AE');
SELECT * FROM CAREERERA1;

COMMIT;

INSERT INTO CAREERERA1 VALUES (4, 104, 'SUNITA', 'SINGHA', 35000, 'PA');
SELECT * FROM CAREERERA1;

ROLLBACK;
SELECT * FROM CAREERERA1;

WHAT DOES SET AUTOCOMMIT=0 ???