CREATE DATABASE STUDENT; # ctreating table

USE STUDENT; # using database

#Create table with columns
CREATE TABLE STUDENT_DETAILS (NAME VARCHAR(20), AGE INT, MARKS FLOAT);

#insert values to columns
INSERT INTO STUDENT_DETAILS (NAME, AGE, MARKS) VALUES ('SURAJ',26,98.5), ('RAM', 24, 78.9), ('BHOOMI', 25, 99.5);

#create new column
ALTER TABLE STUDENT_DETAILS ADD COLUMN PHONE INT;

#insert values
UPDATE STUDENT_DETAILS SET PHONE=872224583 WHERE NAME="SURAJ";
UPDATE STUDENT_DETAILS SET PHONE=461231738 WHERE NAME="RAM";
UPDATE STUDENT_DETAILS SET PHONE=362717238 WHERE NAME="RAM";

SELECT * FROM STUDENT_DETAILS;
