# Common date time functions in MySQL

# Common data type related to datetime
-- 1. DATE 	2. TIME	  3. DATETIME
CREATE TABLE TIME_TABLE (
MY_DATE DATE,
MY_TIME TIME,
MY_DATE_TIME DATETIME
);

SELECT * FROM TIME_TABLE;

# Insert values using function
-- 1. CURRENT_DATE() or CURDATE() - used to get todays date
-- 2. CURRENT_TIME() or CURTIME() - used to get current time
-- 3. NOW() or CURRENT_TIMESTAMP() or CURRENT_TIMESTAMP or LOCALTIME() or LOCALTIMESTAMP() - used to get current date and time

INSERT INTO TIME_TABLE
VALUES (CURRENT_DATE(), CURRENT_TIME(), NOW());
SELECT * FROM TIME_TABLE;

SELECT NOW(), LOCALTIME(), LOCALTIME, LOCALTIMESTAMP(), LOCALTIMESTAMP;

-- 4. DATEDIFF() - 	to get difference between 2 dates
SELECT START_DATE, END_DATE, DATEDIFF(END_DATE, START_DATE) AS DATE_DIFFERENCE FROM JOB_HISTORY;

-- 5. ADDDATE(), ADDTIME() - used to add or time
SELECT ADDDATE('2023-12-31', INTERVAL 0 DAY);
SELECT ADDTIME('2023-12-31 23:59:59.999999', '1 1:1:1.000002');

-- 6. CONVERT_TZ() - convert one timezone to another
SELECT CONVERT_TZ('2004-01-01 12:00:00', 'IST', 'GMT');
SELECT CONVERT_TZ('2004-01-01 12:00:00','GMT','MET');

-- 7. DATE() - extract date part of datetime value
SELECT DATE(ADDTIME('2023-12-31 23:59:59.999999', '1 1:1:1.000002'));

-- 8. DAY(), MONTH(), YEAR(), MONTH(), QURTER(), MONTHNAME(), DAYOFMONTH(), DAYNAME(), DAYOFWEEK(), DAYOFYEAR(), HOUR(), MINUTE(), SECOND()
SELECT DAY('2023-05-08') AS DAY,
	   YEAR('2023-05-08 ') AS YEAR,
       MONTH('2023-05-08') AS MONTH,
       QUARTER('2023-05-08') AS QUARTER,
       MONTHNAME('2023-05-08') AS MONTH_NAME,
	   DAYOFMONTH('2023-05-08') AS DAY_OF_MONTH,
       DAYOFYEAR('2023-05-08') AS DAY_OF_YEAR,
       DAYNAME('2023-05-08') AS DAY_NAME,
       DAYOFWEEK('2023-05-08') AS DAY_OF_WEEK,
       HOUR('2023-05-08 10:05:03') AS HOUR,
       MINUTE('2023-05-08 10:05:03') AS MINUTES,
       SECOND('2023-05-08 10:05:03') AS SECONDS;
       
SELECT HIRE_DATE, DAY(HIRE_DATE) AS DAY,
	   YEAR(HIRE_DATE) AS YEAR,
       MONTH(HIRE_DATE) AS MONTH,
       QUARTER(HIRE_DATE) AS QUARTER,
       MONTHNAME(HIRE_DATE) AS MONTH_NAME,
	   DAYOFMONTH(HIRE_DATE) AS DAY_OF_MONTH,
       DAYOFYEAR(HIRE_DATE) AS DAY_OF_YEAR,
       DAYNAME(HIRE_DATE) AS DAY_NAME,
       DAYOFWEEK(HIRE_DATE) AS DAY_OF_WEEK FROM EMPLOYEES;
       
-- 9. LAST_DAY() - return last date of that month
SELECT LAST_DAY('2023-09-05');

-- 10. MAKEDATE() - create date using year and day of year
SELECT MAKEDATE(2023,31), MAKEDATE(2023,32), MAKEDATE(2023,33);

-- 11. MAKETIME() - creates time using hour, minute and second
SELECT MAKETIME(12,12,45), MAKETIME(15, 49,00);

-- 12. UTC_DATE(), UTC_TIME(), UTC_TIMESTAMP()
SELECT UTC_DATE(), UTC_TIME(), UTC_TIMESTAMP();
