CREATE DATABASE MY_INFO;

USE MY_INFO;

CREATE TABLE PERSONAL_INFO (
NAME VARCHAR(20),
AGE INT,
MOBILE_NUMBER BIGINT,
EMAIL VARCHAR(50),
CITY VARCHAR(20),
STATE VARCHAR(20),
COUNTRY VARCHAR(20)
);

INSERT INTO PERSONAL_INFO
VALUES("SURAJ", 27, 8722245836, "SURAJH8596@GMAIL.COM", "BELGAUM", "KARNATAKA", "INDIA"),
	  ("DHANALAXMI", 27, 7827294782, "DHANALAXMI8596@GMAIL.COM", "BANGALORE", "KARNATAKA", "INDIA"),
      ("RAMAN", 26, 7382947208, "RAMAN67382@GMAIL.COM", "GADAG", "KARNATAKA", "INDIA"),
      ("REEMA", 28, 6378274768, "REMMASINGH@GMAIL.COM", "MUMBAI", "MAHARASTRA", "INDIA"),
      ("JEEVAN", 25, 7839465731, "JEEVANBIMA@GMAIL.COM", "ATHANI", "KARNATAKA", "INDIA"),
      ("TINA", 24, 7835681932, "TINAKKK@GMAIL.COM", "NEW DELHI", "DELHI", "INDIA");
      
SHOW DATABASES;
SHOW SCHEMAS;
SHOW TABLES;
SHOW ERRORS;
SHOW COLUMNS FROM PERSONAL_INFO;
SHOW EVENTS;

-- USING ISNA
-- IF COMMISSION_PCT IN NULL THEN INSERT "UNKNOWN"
USE HR;
SELECT * FROM EMPLOYEES;
SELECT EMPLOYEE_ID, COMMISSION_PCT, IFNULL(COMMISSION_PCT, "UNKNOWN") AS NEW_COMMISSION_PCT FROM EMPLOYEES;

-- TOP 5 ROWS
SELECT * FROM EMPLOYEES LIMIT 5;

-- USING NOT EQUAL TO !=
SELECT * FROM EMPLOYEES WHERE FIRST_NAME !="STEVEN";

SELECT CURRENT_DATE();

SELECT * FROM EMPLOYEES;

USE HR;

SELECT * FROM LOCATIONS;

SELECT CITY, CHAR_LENGTH(CITY) FROM LOCATIONS
WHERE CHAR_LENGTH(CITY)=(SELECT MAX(CHAR_LENGTH(CITY)))
ORDER BY CHAR_LENGTH(CITY) DESC
LIMIT 1;
SELECT CITY, CHAR_LENGTH(CITY) FROM LOCATIONS
WHERE CHAR_LENGTH(CITY)=(SELECT MIN(CHAR_LENGTH(CITY)))
ORDER BY CHAR_LENGTH(CITY)
LIMIT 1;

USE HR;

SELECT * FROM EMPLOYEES;

SELECT MAX(SALARY*COMMISSION_PCT) AS MAX_SALARY, COUNT(SALARY*COMMISSION_PCT) AS MAX_SALARY_COUNT FROM EMPLOYEES
ORDER BY COUNT(SALARY*COMMISSION_PCT) DESC;