USE HR;

SELECT * FROM EMPLOYEES;

DESC EMPLOYEES;

-- DATA TYPE
-- INT - WHOLE NUMBER +VE OR -VE
-- INT UNSIGNED - ONLY +VE WHOLE NUMBER
-- DECIMAL (8,3) 8 IS PRECISION MEANS TOTAL UNIT AND 3 SCALE ( DECIMAL POINTS) PRECISION >SCALE
-- CHAR(10) IF I JUST GIVEN 10 LETERS THEN IT WILL OCCUPY AN UNNECORY SPACE OF 10 HENCE WE DO NOT USE CHAR
-- VARCHAR(10) IF A JUST ENTER 2 LETER THEN IT JUST OCCUPY 2 SPACE
-- DATE 



-- DDL (DATA DEFINITION LANGUAGE) AUTO SAVES ITSELF
-- DDL ON AUTOSAVE 

-- CREATE

CREATE TABLE CAREERERA1 (
EMPLOYEE_ID INT UNSIGNED,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
SALARY DECIMAL(7,2));

SELECT * FROM CAREERERA1;


-- ALTER

ALTER TABLE CAREERERA1 ADD COLUMN DEPARTMENT_NAME VARCHAR(50);
SELECT * FROM CAREERERA1;

ALTER TABLE CAREERERA1 ADD DEPARTMENT_ID INT UNSIGNED, ADD MANAGER_ID INT UNSIGNED;
SELECT * FROM CAREERERA1;

ALTER TABLE CAREERERA1 ADD PHONE_NUMBER VARCHAR(20) AFTER LAST_NAME;
SELECT * FROM CAREERERA1;

ALTER TABLE CAREERERA1 ADD S_NO INT FIRST;
SELECT * FROM CAREERERA1;

-- DROP 

ALTER TABLE CAREERERA1 DROP PHONE_NUMBER;
SELECT * FROM CAREERERA1;

ALTER TABLE CAREERERA1 DROP DEPARTMENT_NAME, DROP MANAGER_ID;
SELECT * FROM CAREERERA1;

-- MODIFY

ALTER TABLE CAREERERA1 MODIFY COLUMN SALARY DECIMAL(10,3);
DESC CAREERERA1;

-- RENAME

ALTER TABLE CAREERERA1 RENAME COLUMN EMPLOYEE_ID TO EMP_ID;
SELECT * FROM CAREERERA1;

-- TRUNCATE

SELECT * FROM EMPLOYEES;

CREATE TABLE EMP_COPY AS ( SELECT * FROM EMPLOYEES WHERE FALSE);
SELECT * FROM EMP_COPY;

-- WHEN WE USE WHERE HERE IN TABLE IT JUST COPY COLUMNS BUT NOT THE DATA
-- WHEN WE NOT USE WHERE IT COPY ALL THE COLUMNS AND DATA

CREATE TABLE EMP_COPY1 AS ( SELECT * FROM EMPLOYEES);
SELECT * FROM EMP_COPY1;

CREATE TABLE EMP_COPY2 AS ( SELECT * FROM EMPLOYEES);
SELECT * FROM EMP_COPY2;

TRUNCATE EMP_COPY2;
SELECT * FROM EMP_COPY2;

-- COMMENT

SELECT * FROM EMP_COPY1;

ALTER TABLE EMP_COPY1 MODIFY COLUMN SALARY VARCHAR(20) COMMENT "IT TELLS ABOUT MONTHLY GROSS SALARY";

ALTER TABLE EMP_COPY1 MODIFY COLUMN EMPLOYEE_ID VARCHAR(20) COMMENT "UNIQUE ID PROVIDED BY THE COMPANY TO THEIR EMPLOYEE";

SHOW FULL COLUMNS FROM EMP_COPY1;


-- DROP THE TABLE

DROP TABLE EMP_COPY2;

DROP TABLE EMP_COPY1;

DROP TABLE EMP_COPY;

