	USE HR;
    
    SELECT * FROM EMPLOYEES;
    
    SELECT * FROM DEPARTMENTS;
    
    -- INNER JOIN
    
    SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
    INNER JOIN
    DEPARTMENTS
    USING (DEPARTMENT_ID);
    
    ALTER TABLE DEPARTMENTS RENAME COLUMN DEPARTMENT_ID TO DEPT_ID;
    
    SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES
    INNER JOIN
    DEPARTMENTS
    ON (DEPARTMENTS.DEPT_ID=EMPLOYEES.DEPARTMENT_ID);
    
	SELECT FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID FROM EMPLOYEES AS E
    INNER JOIN
    DEPARTMENTS AS D
    ON (D.DEPT_ID=E.DEPARTMENT_ID);
    
    ---------------------------------------------------------------------------------------------------------
    USE HR;
    
    SELECT * FROM EMPLOYEES;
    SELECT * FROM DEPARTMENTS;
    
    
    SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME FROM EMPLOYEES
    JOIN DEPARTMENTS ON (DEPARTMENTS.DEPT_ID=EMPLOYEES.DEPARTMENT_ID)
    WHERE DEPARTMENT_ID=10 OR DEPARTMENT_ID=30
    HAVING DEPARTMENT_ID=30;
    
    
    SELECT * FROM COUNTRIES;
    SELECT  COUNT(*) FROM COUNTRIES;
    
    SELECT * FROM LOCATIONS;
    SELECT  COUNT(*) FROM LOCATIONS;
    
    SELECT * FROM REGIONS;
    SELECT  COUNT(*) FROM REGIONS;
    
    SELECT * FROM COUNTRIES JOIN
    LOCATIONS USING (COUNTRY_ID)
    JOIN REGIONS USING (REGION_ID);
    

    -----------------------------------------------------------------------------------------
    
    -- LEFT JOIN
    
    SELECT * FROM REGIONS;
    SELECT * FROM COUNTRIES;
    
    SELECT * FROM COUNTRIES LEFT JOIN REGIONS USING (REGION_ID);
    
    SELECT COUNTRY_NAME, COUNTRY_ID, REGION_ID FROM  COUNTRIES LEFT JOIN REGIONS USING (REGION_ID);
    
    SELECT * FROM COUNTRIES LEFT JOIN REGIONS ON (COUNTRIES.REGION_ID=REGIONS.REGION_ID);
    
    SELECT * FROM COUNTRIES C LEFT JOIN REGIONS R ON (C.REGION_ID=R.REGION_ID);
    
    SELECT * FROM COUNTRIES LEFT JOIN
    LOCATIONS USING (COUNTRY_ID)
	JOIN REGIONS USING (REGION_ID);