USE HR;

CREATE TABLE CAREER1(
EMPLOYEE_ID INT UNSIGNED,
FIRST_NAME VARCHAR(20),
LAST_NAME VARCHAR(20),
SALARY DECIMAL(7,3));

SELECT *FROM CAREER1;
DESC CAREER1;

ALTER TABLE CAREER1 ADD DEPARTMENT_NAME VARCHAR(20);
DESC CAREER1;

ALTER TABLE CAREER1 ADD DEPARTMENT_ID INT, ADD MANAGER_ID INT, ADD COMMISSION_PCT DECIMAL(3,1);
DESC CAREER1;

ALTER TABLE CAREER1 DROP COMMISSION_PCT;
DESC CAREER1;

ALTER TABLE CAREER1 DROP MANAGER_ID, DROP DEPARTMENT_ID, DROP DEPARTMENT_NAME;
DESC CAREER1;

ALTER TABLE CAREER1 MODIFY COLUMN LAST_NAME VARCHAR(40);
DESC CAREER1;

ALTER TABLE CAREER1 RENAME COLUMN LAST_NAME TO SURENAME;
DESC CAREER1;

SELECT *FROM EMPLOYEES;

CREATE TABLE EMP_PRACTICE AS (SELECT * FROM EMPLOYEES);
SELECT * FROM EMP_PRACTICE;

CREATE TABLE EMP_PRACTICE2 AS (SELECT * FROM EMPLOYEES WHERE TRUE);
SELECT *FROM EMP_PRACTICE2;

CREATE TABLE EMP_PRACTICE1 AS (SELECT * FROM EMPLOYEES WHERE FALSE);
SELECT *FROM EMP_PRACTICE1;

TRUNCATE EMP_PRACTICE2;
SELECT *FROM EMP_PRACTICE2;

SHOW FULL COLUMNS from EMPLOYEES;

ALTER TABLE EMPLOYEES MODIFY COLUMN JOB_ID VARCHAR(10) COMMENT "THIS IS THE JOB ROLE OF EMPLOYEE";
SHOW FULL COLUMNS from EMPLOYEES;

DROP TABLE EMP_PRACTICE2;
SELECT * FROM EMP_PRACTICE2;

RENAME TABLE EMP_PRACTICE1 TO EMP_PRACTICE2;
SELECT * FROM EMP_PRACTICE2;

RENAME TABLE EMP_PRACTICE TO EMP_PRACTICE1;
SELECT * FROM EMP_PRACTICE1;

