USE EMPLOYEE; #OLD DATABASE NAME
CREATE DATABASE EMPLOYEES; #NEW DATABASE CREATION
USE EMPLOYEES; #NEW DATABASE IN USE
CREATE TABLE EMPLOYEES.EMPLOYEES_INFO AS SELECT * FROM EMPLOYEE.EMPLOYEES_INFO; #COPYING OLD DATABSE TABLE TO NEW DATABASE
SELECT * FROM EMPLOYEES_INFO; #CHECK TABLE VALUES
DROP DATABASE EMPLOYEE;